repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.4.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: detect-private-key
      - id: check-ast
  - repo: local
    hooks:
       - id: flake8
         name: flake8
         entry: flake8
         language: system
         types: [python]
       - id: black
         name: black
         entry: black
         language: system
         types: [python]
         args: [--skip-string-normalization, --line-length=120]
       - id: pytest
         name: pytest
         entry: pytest
         language: system
         types: [python]
         args: [--cov-fail-under=95, --cov=./src/api, ./src/tests]
