version: '3.8'
services:
  db:
    image: postgres:13.3
    env_file:
      - .env.docker
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "54321:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    restart: on-failure
    ports:
      - "5001:5000"
    volumes:
      - ./src/api:/digeizTechTask/api
      - ./src/main.py:/digeizTechTask/main.py
    depends_on:
      - db