"""not null constraint

Revision ID: ac7779fcbd36
Revises: c46a5ce125bc
Create Date: 2023-02-12 21:10:17.226218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7779fcbd36'
down_revision = 'c46a5ce125bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mall', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('unit', 'mall_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unit', 'mall_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mall', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
