"""unique_constraints

Revision ID: c46a5ce125bc
Revises: efb13363e76a
Create Date: 2023-02-12 20:57:24.853610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c46a5ce125bc'
down_revision = 'efb13363e76a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'mall', ['name'])
    op.create_unique_constraint(None, 'unit', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit', type_='unique')
    op.drop_constraint(None, 'mall', type_='unique')
    # ### end Alembic commands ###
